version: '3'
services:

  jaeger:
    image: jaegertracing/all-in-one:1.12
    ports:
      - 16686:16686

  recursed:
    image: gregoryguillou/recursed:0.4.1
    environment:
      JAEGER_SERVICE_NAME: recurse
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: "6831"
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: "1"
      JAEGER_REPORTER_LOG_SPANS: "true"
    ports:
      - 8000:8000
    command:
      - ./recursed
    depends_on:
      - jaeger
